baseurl = "https://mossbauer.mtholyoke.edu/"
page_string = "?pageNo="

#~ mt holyoke categories
categories = [
    "group/Allophane",
    "group/Alunite",
    "group/Amphibole",
    "group/Axinite",
    "group/Beryl",
    "group/Biogeochemical+Mineralogical+By-Products",
    "group/Biotite",
    "group/Carbonate",
    "group/Chlorite",
    "group/Clay",
    "group/Cordierite",
    "group/Fe+metal",
    "group/Feldspar",
    "group/Ferricopiapite",
    "group/Fulgurite",
    "group/Garnet",
    "group/Glass",
    "group/Halide",
    "group/Hydroxide",
    "group/Ilmenite",
    "group/Industrial+Samples",
    "group/Jarosite",
    "group/Kaolinite-Serpentine",
    "group/Metal",
    "group/Meteorite",
    "group/Mica",
    "group/Miscellaneous",
    "group/Mixtures",
    "group/Modulated+Phyllosilicates",
    "group/Multiple+Oxide",
    "group/Olivine",
    "group/Oxide",
    "group/Phosphate",
    "group/Pumpellyite",
    "group/Pyrophyllite-Talc",
    "group/Pyroxene",
    "group/Scapolite",
    "group/SiO2",
    "group/Smectite",
    "group/Staurolite",
    "group/Sulfate",
    "group/Sulfide",
    "group/Sulfite",
    "group/Talc",
    "group/Terrestrial+Samples",
    "group/Titanite",
    "group/Tourmaline",
    "group/Zircon",
    "group/beryl",
    "group/clay",
    "group/glass",
    "group/hydroxide",
    "group/lunar",
    "group/n%2Fa",
    "group/na",
    "group/oxide",
    "group/pyroxene",
    "group/rock",
    "group/sulfide",
    "group/unkwn",
    "group/weathered+steel",]


fields_to_extract = []
